### ISSUE TITLE
Run the software

### ISSUE THREAD

**Issue by edwardtheharris** [edwardtheharris/helm-nautobot#11]
- [x] https://github.com/edwardtheharris/helm-nautobot/issues/21
While also having the software do something other than display debug info

**Comment by edwardtheharris** [comment]
We'll need to get the GitHub SSO working at some point, but for new let's just use the default auth backend, since that looks like the source of the current issue.

**Comment by edwardtheharris** [comment]
```sh
[2024-08-06 16:33:36,401: ERROR/MainProcess] Signal handler <function setup_prometheus at 0x7585cc3bf9c0> raised: AttributeError("'Settings' object has no attribute 'CELERY_WORKER_PROMETHEUS_PORTS'")
Traceback (most recent call last):
  File "/opt/celery/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/celery/lib/python3.11/site-packages/nautobot/core/celery/__init__.py", line 149, in setup_prometheus
    if not settings.CELERY_WORKER_PROMETHEUS_PORTS:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/celery/lib/python3.11/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Settings' object has no attribute 'CELERY_WORKER_PROMETHEUS_PORTS'
```

Going to need to fix this.
